# Generated by Django 2.2.6 on 2020-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroApi', '0002_auto_20200512_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
