# Generated by Django 2.2.6 on 2020-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroApi', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='MediaPosts'),
        ),
    ]
