# Generated by Django 3.0.4 on 2020-05-14 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AgroApi', '0004_auto_20200512_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='joined',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='AgroApi.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='tag',
            field=models.CharField(choices=[('Research', 'Research'), ('Farming', 'Farming'), ('Agro Buisness', 'Agro Buisness')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, upload_to='MediaPosts'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
